### ISSUE TITLE
Format layer legends correctly when in mobile mode

### ISSUE THREAD

**Issue by ColinAnthony** [codebridge-za/seeking-shelter#28]

**Comment by rikusv** [comment]
In order to make the legend SVGs responsive, we need to add the `viewBox` attribute. I can't see how to do this with folium (seems to be hard-coded: https://github.com/python-visualization/branca/blob/a2e22815eea5a96d9bf3b08fd0cfb10c6f3c3de6/branca/templates/color_scale.js). An ugly workaround is to do this in `build.py`:

```python
map_content = map_content.replace('.attr("width", 450)', '.attr("viewBox", "0 0 450 40");')
map_content = map_content.replace('.attr("height", 40);', '')
```

Should I go ahead with the above, or am I missing a better option...?
